/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaassignment;

/**
 *
 * @author yipzh
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPersonalProfile = new javax.swing.JButton();
        btnWorkerProfile = new javax.swing.JButton();
        btnWorkDoneReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnApprovedSalesReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPersonalProfile.setText("Manage Personal Profile");
        btnPersonalProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalProfileActionPerformed(evt);
            }
        });

        btnWorkerProfile.setText("Manage Worker Profile");
        btnWorkerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerProfileActionPerformed(evt);
            }
        });

        btnWorkDoneReport.setText("Generate Work Done Report");
        btnWorkDoneReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkDoneReportActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnApprovedSalesReport.setText("Generate Approved Sales Report");
        btnApprovedSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedSalesReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnApprovedSalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWorkDoneReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWorkerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPersonalProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnPersonalProfile)
                .addGap(18, 18, 18)
                .addComponent(btnWorkerProfile)
                .addGap(18, 18, 18)
                .addComponent(btnApprovedSalesReport)
                .addGap(18, 18, 18)
                .addComponent(btnWorkDoneReport)
                .addGap(38, 38, 38)
                .addComponent(btnLogout)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalProfileActionPerformed
        // TODO add your handling code here:
        PersonalProfile a = new PersonalProfile();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPersonalProfileActionPerformed

    private void btnWorkerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerProfileActionPerformed
        // TODO add your handling code here:
        WorkerProfile a = new WorkerProfile();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWorkerProfileActionPerformed

    private void btnWorkDoneReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkDoneReportActionPerformed
        // TODO add your handling code here:
        GenerateWorkDoneReport a = new GenerateWorkDoneReport();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWorkDoneReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login a = new Login();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnApprovedSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedSalesReportActionPerformed
        // TODO add your handling code here:
        GenerateApprovedSalesReport a = new GenerateApprovedSalesReport();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnApprovedSalesReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovedSalesReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonalProfile;
    private javax.swing.JButton btnWorkDoneReport;
    private javax.swing.JButton btnWorkerProfile;
    // End of variables declaration//GEN-END:variables
}
